
class MyExc : System.Exception {
}

class MyExc1 : System.Exception {
}

class MyExc2 : System.Exception {
}

module NoCutoff {
  public Run () : void {
    try {
      try {
        throw MyExc ();
      }
      catch {
        | _ : MyExc =>
          System.Console.WriteLine ("catched first level");
          throw MyExc1 ();
      }
    }
    catch {
      | _ : MyExc1 => System.Console.WriteLine ("catched second level");
    }
  }
}

class X {
  static foo (x : int) : void
  {
    | 0 => throw MyExc ();
    | 1 => throw MyExc1 ();
    | _ => throw MyExc2 ();
  }

  static foo1 (x : int) : void {
    try {
      foo (x);
    }
    catch {
      | e : MyExc => throw e;
      | _ : MyExc1 => throw;
    }
  }

  
  static Main () :  void
  {
    for (mutable i = 0; i < 3; i++) {
      try {
        System.Console.WriteLine (i);
        foo1 (i);
      }
      catch {
        | e : System.Exception =>
          System.Console.WriteLine (e.GetType ());
      }
    }
    NoCutoff.Run ();
  }
}

/*
BEGIN-OUTPUT
0
MyExc
1
MyExc1
2
MyExc2
catched first level
catched second level
END-OUTPUT
*/
